name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Deploy Backend
        working-directory: ./backend
        run: |
          doctl apps update <backend-app-id> \
            --spec ./backend/do-app.yaml

      - name: Deploy Frontend
        working-directory: ./frontend
        run: |
          doctl apps update <frontend-app-id> \
            --spec ./frontend/do-app.yaml
